OUTLIERS -> (similar to slicing and indexing)
as we do indexing and slicing to get elements in arrays and list
we use loc and iloc in pandas dataframs

LOC -> label based indexing
iLOC -> label based indexing

In [1]:
import pandas as pd
df = pd.read_csv('/home/harsh/Documents/jNotebook/Pandas/customer_data.csv')

In [2]:
df

,id,customer_name,age,gender,region,occupation,purchase_amount,loyalty_program,preferred_category,delivery_preference
0,1,Alice Thompson,25,Female,North,Engineer,150.75,Yes,Electronics,Express
1,2,Robert Lee,32,Male,South,Teacher,89.50,No,Clothing,Standard
2,3,Emily Chen,28,Female,West,Designer,220.30,Yes,Home Decor,Express
3,4,Michael Patel,45,Male,East,Manager,175.20,No,Electronics,Standard
4,5,Sophia Nguyen,19,Female,North,Student,65.10,Yes,Books,Express
...,...,...,...,...,...,...,...,...,...,...
95,96,Aliyah Holmes,29,Female,North,Analyst,145.60,Yes,Books,Express
96,97,Declan Porter,42,Male,South,Engineer,195.25,No,Electronics,Standard
97,98,Sienna Riley,26,Female,West,Student,85.30,Yes,Home Decor,Express
98,99,Asher Wallace,34,Male,East,Teacher,160.75,No,Clothing,Standard
99,100,Clara Dixon,28,Female,North,Artist,90.40,Yes,Books,Express

In [3]:
#3. Select 'customer_name' and 'purchase_amount' for customers in the North region.
df.loc[df['region'] == 'North' , ['customer_name','purchase_amount','region']]

      customer_name  purchase_amount region
0    Alice Thompson           150.75  North
4     Sophia Nguyen            65.10  North
8      Ava Martinez            95.25  North
12        Mia Lewis           110.15  North
16     Amelia Allen            70.20  North
20     Evelyn Adams            85.30  North
24   Emily Mitchell           135.60  North
28   Sofia Phillips           115.30  North
32  Madison Edwards            90.50  North
36        Zoey Reed           130.95  North
40     Riley Brooks            80.15  North
44       Hannah Cox           125.80  North
48   Natalie Fisher            95.40  North
52       Hazel West           140.15  North
55     Aubrey Myers           130.80  North
59    Arianna Price           145.15  North
63   Aurora Jenkins            90.80  North
67      Clara Wells           140.65  North
71      Maya Hunter           135.40  North
75       Lydia Cole            90.25  North
79    Aria Peterson            85.15  North
83  Addison Simmons           130.70  North
87      Autumn Ford           125.20  North
91       Audrey Fox           135.85  North
95    Aliyah Holmes           145.60  North
99      Clara Dixon            90.40  North

In [4]:
df.query('id == 15') #1. Select all columns for the customer with id 15.
df.loc[df['id']==15, :]

,id,customer_name,age,gender,region,occupation,purchase_amount,loyalty_program,preferred_category,delivery_preference
14,15,Charlotte Hall,26,Female,West,Designer,130.85,Yes,Home Decor,Express

In [5]:
#2. Select the first 10 rows and the first 4 columns of the dataset.
df.iloc[0:11,0:4]

    id   customer_name  age  gender
0    1  Alice Thompson   25  Female
1    2      Robert Lee   32    Male
2    3      Emily Chen   28  Female
3    4   Michael Patel   45    Male
4    5   Sophia Nguyen   19  Female
5    6    James Wilson   37    Male
6    7    Olivia Brown   29  Female
7    8  William Garcia   52    Male
8    9    Ava Martinez   23  Female
9   10      Liam Davis   41    Male
10  11  Isabella Clark   30  Female

In [6]:
#4. Select the last 15 rows and columns 3 through 6.
df.iloc[-15:, 3:7]

    gender region  occupation  purchase_amount
85  Female   West      Artist            95.50
86    Male   East    Engineer           190.65
87  Female  North     Teacher           125.20
88    Male  South      Doctor           285.75
89  Female   West     Student            80.90
90    Male   East  Consultant           210.30
91  Female  North   Marketing           135.85
92    Male  South     Manager           245.40
93  Female   West    Designer           130.95
94    Male   East      Lawyer           170.50
95  Female  North     Analyst           145.60
96    Male  South    Engineer           195.25
97  Female   West     Student            85.30
98    Male   East     Teacher           160.75
99  Female  North      Artist            90.40

In [7]:
#5. Select all columns for customers with purchase_amount greater than 200.
df.loc[df['purchase_amount']>200,:]

,id,customer_name,age,gender,region,occupation,purchase_amount,loyalty_program,preferred_category,delivery_preference
2,3,Emily Chen,28,Female,West,Designer,220.30,Yes,Home Decor,Express
5,6,James Wilson,37,Male,South,Doctor,300.80,No,Clothing,Standard
7,8,William Garcia,52,Male,East,Consultant,200.60,No,Electronics,Standard
13,14,Ethan Walker,38,Male,South,Manager,250.40,No,Clothing,Standard
15,16,Alexander Young,49,Male,East,Doctor,280.95,No,Electronics,Standard
19,20,Henry Green,44,Male,East,Consultant,210.25,No,Home Decor,Standard
25,26,Benjamin Perez,46,Male,South,Manager,230.75,No,Clothing,Standard
29,30,Elijah Campbell,40,Male,South,Doctor,270.85,No,Clothing,Standard
31,32,Logan Evans,43,Male,East,Consultant,205.65,No,Electronics,Standard
35,36,Samuel Morris,48,Male,East,Manager,240.80,No,Electronics,Standard
39,40,Joseph Bell,41,Male,East,Doctor,275.20,No,Electronics,Standard
41,42,Carter Cooper,39,Male,South,Consultant,210.50,No,Clothing,Standard
47,48,Isaac Wood,42,Male,East,Manager,235.25,No,Home Decor,Standard
51,52,Julian Hughes,47,Male,East,Doctor,280.30,No,Electronics,Standard
56,57,Jaxon Kelly,44,Male,South,Consultant,215.45,No,Electronics,Standard
60,61,Connor Griffin,41,Male,South,Manager,240.70,No,Electronics,Standard
64,65,Christian Marshall,48,Male,South,Doctor,285.40,No,Electronics,Standard
68,69,Tristan Sullivan,42,Male,South,Consultant,210.20,No,Electronics,Standard
72,73,Micah Andrews,46,Male,South,Manager,245.75,No,Electronics,Standard
76,77,Isaiah Barnes,43,Male,South,Doctor,280.60,No,Electronics,Standard
80,81,Easton Jordan,40,Male,South,Consultant,215.90,No,Electronics,Standard
84,85,Colton Freeman,44,Male,South,Manager,240.15,No,Electronics,Standard
88,89,Nathan Hart,41,Male,South,Doctor,285.75,No,Electronics,Standard
90,91,Adrian Black,39,Male,East,Consultant,210.30,No,Clothing,Standard
92,93,Caleb Gardner,45,Male,South,Manager,245.40,No,Electronics,Standard

In [8]:
#6. Select every third row from the first 30 rows and columns 0, 2, and 5.
index =0;
while(index <=30):
    
    print(df.iloc[[index],[0,2,5]])
    index += 4

   id  age occupation
0   1   25   Engineer
   id  age occupation
4   5   19    Student
   id  age occupation
8   9   23     Artist
    id  age occupation
12  13   34    Teacher
    id  age occupation
16  17   21    Student
    id  age occupation
20  21   24     Artist
    id  age occupation
24  25   27   Designer
    id  age occupation
28  29   29    Analyst

In [9]:
#6. Select every third row from the first 30 rows and columns 0, 2, and 5.
df.iloc[2:31:3,[0,2,5]]

    id  age occupation
2    3   28   Designer
5    6   37     Doctor
8    9   23     Artist
11  12   27   Engineer
14  15   26   Designer
17  18   33    Analyst
20  21   24     Artist
23  24   39    Teacher
26  27   22    Student
29  30   40     Doctor

In [10]:
#7. Select 'customer_name', 'age', and 'occupation' for customers with gender 'Female'.
df.loc[df['gender'] == 'Female', ['customer_name','age', 'occupation']]

       customer_name  age occupation
0     Alice Thompson   25   Engineer
2         Emily Chen   28   Designer
4      Sophia Nguyen   19    Student
6       Olivia Brown   29    Analyst
8       Ava Martinez   23     Artist
10    Isabella Clark   30  Marketing
12         Mia Lewis   34    Teacher
14    Charlotte Hall   26   Designer
16      Amelia Allen   21    Student
18      Harper Scott   28   Engineer
20      Evelyn Adams   24     Artist
22    Abigail Nelson   31  Marketing
24    Emily Mitchell   27   Designer
26     Avery Roberts   22    Student
28    Sofia Phillips   29    Analyst
30      Grace Parker   26  Marketing
32   Madison Edwards   23     Artist
34     Layla Stewart   30    Teacher
36         Zoey Reed   25   Designer
38   Penelope Morgan   28    Analyst
40      Riley Brooks   24    Student
42       Aria Bailey   27  Marketing
44        Hannah Cox   29   Designer
46     Stella Butler   31   Engineer
48    Natalie Fisher   26     Artist
50     Victoria Gray   24    Student
52        Hazel West   28  Marketing
54      Lillian Ford   30    Teacher
55      Aubrey Myers   27   Designer
57        Ellie Long   23    Student
59     Arianna Price   26    Analyst
61  Savannah Sanders   29  Marketing
63    Aurora Jenkins   24     Artist
65      Skylar Ortiz   27   Designer
67       Clara Wells   30    Analyst
69     Delilah Hayes   25    Student
71       Maya Hunter   28  Marketing
73       Nora Hudson   26   Designer
75        Lydia Cole   24     Artist
77   Eleanor Russell   29    Teacher
79     Aria Peterson   27    Student
81       Lila Murray   25  Marketing
83   Addison Simmons   30   Designer
85    Paisley Pierce   26     Artist
87       Autumn Ford   28    Teacher
89     Brooklyn Dunn   24    Student
91        Audrey Fox   27  Marketing
93       Piper Ellis   25   Designer
95     Aliyah Holmes   29    Analyst
97      Sienna Riley   26    Student
99       Clara Dixon   28     Artist

In [11]:
#8. Select the 20th to 25th rows (inclusive) and the last 4 columns.
df.loc[20:25,['purchase_amount','loyalty_program','preferred_category','delivery_preference']]

    purchase_amount loyalty_program preferred_category delivery_preference
20            85.30             Yes              Books             Express
21           170.80              No           Clothing            Standard
22           125.90             Yes         Home Decor             Express
23           155.45              No        Electronics            Standard
24           135.60             Yes              Books             Express
25           230.75              No           Clothing            Standard

In [12]:
#9. Select all columns for customers enrolled in the loyalty program (loyalty_program = 'Yes').
df.loc[df['loyalty_program'] == 'Yes', :]

,id,customer_name,age,gender,region,occupation,purchase_amount,loyalty_program,preferred_category,delivery_preference
0,1,Alice Thompson,25,Female,North,Engineer,150.75,Yes,Electronics,Express
2,3,Emily Chen,28,Female,West,Designer,220.30,Yes,Home Decor,Express
4,5,Sophia Nguyen,19,Female,North,Student,65.10,Yes,Books,Express
6,7,Olivia Brown,29,Female,West,Analyst,120.45,Yes,Home Decor,Express
8,9,Ava Martinez,23,Female,North,Artist,95.25,Yes,Books,Express
10,11,Isabella Clark,30,Female,West,Marketing,140.70,Yes,Home Decor,Express
12,13,Mia Lewis,34,Female,North,Teacher,110.15,Yes,Books,Express
14,15,Charlotte Hall,26,Female,West,Designer,130.85,Yes,Home Decor,Express
16,17,Amelia Allen,21,Female,North,Student,70.20,Yes,Books,Express
18,19,Harper Scott,28,Female,West,Engineer,190.50,Yes,Electronics,Express
20,21,Evelyn Adams,24,Female,North,Artist,85.30,Yes,Books,Express
22,23,Abigail Nelson,31,Female,West,Marketing,125.90,Yes,Home Decor,Express
24,25,Emily Mitchell,27,Female,North,Designer,135.60,Yes,Books,Express
26,27,Avery Roberts,22,Female,West,Student,75.15,Yes,Home Decor,Express
28,29,Sofia Phillips,29,Female,North,Analyst,115.30,Yes,Books,Express
30,31,Grace Parker,26,Female,West,Marketing,140.40,Yes,Home Decor,Express
32,33,Madison Edwards,23,Female,North,Artist,90.50,Yes,Books,Express
34,35,Layla Stewart,30,Female,West,Teacher,120.70,Yes,Home Decor,Express
36,37,Zoey Reed,25,Female,North,Designer,130.95,Yes,Books,Express
38,39,Penelope Morgan,28,Female,West,Analyst,145.35,Yes,Home Decor,Express
40,41,Riley Brooks,24,Female,North,Student,80.15,Yes,Books,Express
42,43,Aria Bailey,27,Female,West,Marketing,135.65,Yes,Home Decor,Express
44,45,Hannah Cox,29,Female,North,Designer,125.80,Yes,Books,Express
46,47,Stella Butler,31,Female,West,Engineer,190.90,Yes,Electronics,Express
48,49,Natalie Fisher,26,Female,North,Artist,95.40,Yes,Books,Express
50,51,Victoria Gray,24,Female,West,Student,85.75,Yes,Home Decor,Express
52,53,Hazel West,28,Female,North,Marketing,140.15,Yes,Books,Express
54,55,Lillian Ford,30,Female,West,Teacher,120.25,Yes,Home Decor,Express
55,56,Aubrey Myers,27,Female,North,Designer,130.80,Yes,Books,Express
57,58,Ellie Long,23,Female,West,Student,75.90,Yes,Home Decor,Express
59,60,Arianna Price,26,Female,North,Analyst,145.15,Yes,Books,Express
61,62,Savannah Sanders,29,Female,West,Marketing,135.30,Yes,Home Decor,Express
63,64,Aurora Jenkins,24,Female,North,Artist,90.80,Yes,Books,Express
65,66,Skylar Ortiz,27,Female,West,Designer,125.95,Yes,Home Decor,Express
67,68,Clara Wells,30,Female,North,Analyst,140.65,Yes,Books,Express
69,70,Delilah Hayes,25,Female,West,Student,80.35,Yes,Home Decor,Express
71,72,Maya Hunter,28,Female,North,Marketing,135.40,Yes,Books,Express
73,74,Nora Hudson,26,Female,West,Designer,130.10,Yes,Home Decor,Express
75,76,Lydia Cole,24,Female,North,Artist,90.25,Yes,Books,Express
77,78,Eleanor Russell,29,Female,West,Teacher,120.45,Yes,Home Decor,Express
79,80,Aria Peterson,27,Female,North,Student,85.15,Yes,Books,Express
81,82,Lila Murray,25,Female,West,Marketing,140.25,Yes,Home Decor,Express
83,84,Addison Simmons,30,Female,North,Designer,130.70,Yes,Books,Express
85,86,Paisley Pierce,26,Female,West,Artist,95.50,Yes,Home Decor,Express
87,88,Autumn Ford,28,Female,North,Teacher,125.20,Yes,Books,Express
89,90,Brooklyn Dunn,24,Female,West,Student,80.90,Yes,Home Decor,Express
91,92,Audrey Fox,27,Female,North,Marketing,135.85,Yes,Books,Express
93,94,Piper Ellis,25,Female,West,Designer,130.95,Yes,Home Decor,Express
95,96,Aliyah Holmes,29,Female,North,Analyst,145.60,Yes,Books,Express
97,98,Sienna Riley,26,Female,West,Student,85.30,Yes,Home Decor,Express
99,100,Clara Dixon,28,Female,North,Artist,90.40,Yes,Books,Express

In [13]:
#10. Select the first 5 columns for rows 10 to 20.
df.iloc[10:21, 0:5]

    id    customer_name  age  gender region
10  11   Isabella Clark   30  Female   West
11  12   Noah Rodriguez   27    Male   East
12  13        Mia Lewis   34  Female  North
13  14     Ethan Walker   38    Male  South
14  15   Charlotte Hall   26  Female   West
15  16  Alexander Young   49    Male   East
16  17     Amelia Allen   21  Female  North
17  18      Daniel King   33    Male  South
18  19     Harper Scott   28  Female   West
19  20      Henry Green   44    Male   East
20  21     Evelyn Adams   24  Female  North

In [14]:
#11. Select 'customer_name' and 'preferred_category' for customers with purchase_amount above 150.
df.loc[df['purchase_amount'] > 150, ['customer_name','preferred_category', 'purchase_amount']]

         customer_name preferred_category  purchase_amount
0       Alice Thompson        Electronics           150.75
2           Emily Chen         Home Decor           220.30
3        Michael Patel        Electronics           175.20
5         James Wilson           Clothing           300.80
7       William Garcia        Electronics           200.60
9           Liam Davis           Clothing           180.90
11      Noah Rodriguez        Electronics           160.35
13        Ethan Walker           Clothing           250.40
15     Alexander Young        Electronics           280.95
18        Harper Scott        Electronics           190.50
19         Henry Green         Home Decor           210.25
21         Lucas Baker           Clothing           170.80
23         Jack Carter        Electronics           155.45
25      Benjamin Perez           Clothing           230.75
27        Mason Turner        Electronics           195.20
29     Elijah Campbell           Clothing           270.85
31         Logan Evans        Electronics           205.65
33       Aiden Collins           Clothing           165.25
35       Samuel Morris        Electronics           240.80
37          David Cook           Clothing           185.10
39         Joseph Bell        Electronics           275.20
41       Carter Cooper           Clothing           210.50
43         Owen Rivera        Electronics           160.30
45           Luke Ward           Clothing           170.45
46       Stella Butler        Electronics           190.90
47          Isaac Wood         Home Decor           235.25
49       Grayson Stone           Clothing           150.60
51       Julian Hughes        Electronics           280.30
53          Levi Perry           Clothing           195.50
56         Jaxon Kelly        Electronics           215.45
58      Lincoln Foster           Clothing           175.60
60      Connor Griffin        Electronics           240.70
62         Joshua Ross           Clothing           190.25
64  Christian Marshall        Electronics           285.40
66     Jeremiah Gordon           Clothing           160.50
68    Tristan Sullivan        Electronics           210.20
70       Eli Henderson           Clothing           170.85
72       Micah Andrews        Electronics           245.75
74        Aaron Bryant           Clothing           195.30
76       Isaiah Barnes        Electronics           280.60
78       Hudson Duncan           Clothing           150.80
80       Easton Jordan        Electronics           215.90
82           Ezra Reid           Clothing           175.35
84      Colton Freeman        Electronics           240.15
86          Evan Berry           Clothing           190.65
88         Nathan Hart        Electronics           285.75
90        Adrian Black           Clothing           210.30
92       Caleb Gardner        Electronics           245.40
94         Kayden Boyd           Clothing           170.50
96       Declan Porter        Electronics           195.25
98       Asher Wallace           Clothing           160.75

In [15]:
#12. Select rows 40 to 50 and columns 'customer_name', 'gender', and 'delivery_preference' by their index positions.
df.iloc[40:51, [1,3,-1]]

     customer_name  gender delivery_preference
40    Riley Brooks  Female             Express
41   Carter Cooper    Male            Standard
42     Aria Bailey  Female             Express
43     Owen Rivera    Male            Standard
44      Hannah Cox  Female             Express
45       Luke Ward    Male            Standard
46   Stella Butler  Female             Express
47      Isaac Wood    Male            Standard
48  Natalie Fisher  Female             Express
49   Grayson Stone    Male            Standard
50   Victoria Gray  Female             Express

In [16]:
#13. Select all columns for customers aged 25 who prefer 'Books' as their category.
df.loc[(df['age'] == 25) and (df['preferred_category'] == 'Books'),:]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [17]:
#13. Select all columns for customers aged 25 who prefer 'Books' as their category.
df.loc[(df['age'] == 25) & (df['preferred_category'] == 'Books'),:]

,id,customer_name,age,gender,region,occupation,purchase_amount,loyalty_program,preferred_category,delivery_preference
36,37,Zoey Reed,25,Female,North,Designer,130.95,Yes,Books,Express

In [18]:
#14. Select the 6th column for the first 30 rows.
df.iloc[0:31,5]

0       Engineer
1        Teacher
2       Designer
3        Manager
4        Student
5         Doctor
6        Analyst
7     Consultant
8         Artist
9         Lawyer
10     Marketing
11      Engineer
12       Teacher
13       Manager
14      Designer
15        Doctor
16       Student
17       Analyst
18      Engineer
19    Consultant
20        Artist
21        Lawyer
22     Marketing
23       Teacher
24      Designer
25       Manager
26       Student
27      Engineer
28       Analyst
29        Doctor
30     Marketing
Name: occupation, dtype: object

In [19]:
#15. Select 'customer_name', 'purchase_amount', and 'region' for customers with delivery_preference 'Express'.
df.loc[df['delivery_preference'] == 'Express', ['customer_name', 'purchase_amount']]

       customer_name  purchase_amount
0     Alice Thompson           150.75
2         Emily Chen           220.30
4      Sophia Nguyen            65.10
6       Olivia Brown           120.45
8       Ava Martinez            95.25
10    Isabella Clark           140.70
12         Mia Lewis           110.15
14    Charlotte Hall           130.85
16      Amelia Allen            70.20
18      Harper Scott           190.50
20      Evelyn Adams            85.30
22    Abigail Nelson           125.90
24    Emily Mitchell           135.60
26     Avery Roberts            75.15
28    Sofia Phillips           115.30
30      Grace Parker           140.40
32   Madison Edwards            90.50
34     Layla Stewart           120.70
36         Zoey Reed           130.95
38   Penelope Morgan           145.35
40      Riley Brooks            80.15
42       Aria Bailey           135.65
44        Hannah Cox           125.80
46     Stella Butler           190.90
48    Natalie Fisher            95.40
50     Victoria Gray            85.75
52        Hazel West           140.15
54      Lillian Ford           120.25
55      Aubrey Myers           130.80
57        Ellie Long            75.90
59     Arianna Price           145.15
61  Savannah Sanders           135.30
63    Aurora Jenkins            90.80
65      Skylar Ortiz           125.95
67       Clara Wells           140.65
69     Delilah Hayes            80.35
71       Maya Hunter           135.40
73       Nora Hudson           130.10
75        Lydia Cole            90.25
77   Eleanor Russell           120.45
79     Aria Peterson            85.15
81       Lila Murray           140.25
83   Addison Simmons           130.70
85    Paisley Pierce            95.50
87       Autumn Ford           125.20
89     Brooklyn Dunn            80.90
91        Audrey Fox           135.85
93       Piper Ellis           130.95
95     Aliyah Holmes           145.60
97      Sienna Riley            85.30
99       Clara Dixon            90.40

In [20]:
#16. Select rows 5, 15, 25, 35, and 45 and columns 1, 4, and 7.
df.iloc[[4,14,24,35],[0,3,6]]

    id  gender  purchase_amount
4    5  Female            65.10
14  15  Female           130.85
24  25  Female           135.60
35  36    Male           240.80

In [21]:
#17. Select all columns for customers whose names start with 'S'.


for i in range (len(df['customer_name'])):
    if(df['customer_name'][i][0] == 'S'):
        print(df.loc[i,])

id                                 5
customer_name          Sophia Nguyen
age                               19
gender                        Female
region                         North
occupation                   Student
purchase_amount                 65.1
loyalty_program                  Yes
preferred_category             Books
delivery_preference          Express
Name: 4, dtype: object
id                                 29
customer_name          Sofia Phillips
age                                29
gender                         Female
region                          North
occupation                    Analyst
purchase_amount                 115.3
loyalty_program                   Yes
preferred_category              Books
delivery_preference           Express
Name: 28, dtype: object
id                                36
customer_name          Samuel Morris
age                               48
gender                          Male
region                          East
occupation                   Manager
purchase_amount                240.8
loyalty_program                   No
preferred_category       Electronics
delivery_preference         Standard
Name: 35, dtype: object
id                                47
customer_name          Stella Butler
age                               31
gender                        Female
region                          West
occupation                  Engineer
purchase_amount                190.9
loyalty_program                  Yes
preferred_category       Electronics
delivery_preference          Express
Name: 46, dtype: object
id                                   62
customer_name          Savannah Sanders
age                                  29
gender                           Female
region                             West
occupation                    Marketing
purchase_amount                   135.3
loyalty_program                     Yes
preferred_category           Home Decor
delivery_preference             Express
Name: 61, dtype: object
id                               66
customer_name          Skylar Ortiz
age                              27
gender                       Female
region                         West
occupation                 Designer
purchase_amount              125.95
loyalty_program                 Yes
preferred_category       Home Decor
delivery_preference         Express
Name: 65, dtype: object
id                               98
customer_name          Sienna Riley
age                              26
gender                       Female
region                         West
occupation                  Student
purchase_amount                85.3
loyalty_program                 Yes
preferred_category       Home Decor
delivery_preference         Express
Name: 97, dtype: object

In [23]:
#17. Select all columns for customers whose names start with 'S'.
rf = pd.DataFrame(columns = df.columns)
count = 0
for i in range (len(df['customer_name'])):
    if(df['customer_name'][i][0] == 'S'):
        rf.loc[len(rf)] = df.loc[i,]

rf

,id,customer_name,age,gender,region,occupation,purchase_amount,loyalty_program,preferred_category,delivery_preference
0,5,Sophia Nguyen,19,Female,North,Student,65.1,Yes,Books,Express
1,29,Sofia Phillips,29,Female,North,Analyst,115.3,Yes,Books,Express
2,36,Samuel Morris,48,Male,East,Manager,240.8,No,Electronics,Standard
3,47,Stella Butler,31,Female,West,Engineer,190.9,Yes,Electronics,Express
4,62,Savannah Sanders,29,Female,West,Marketing,135.3,Yes,Home Decor,Express
5,66,Skylar Ortiz,27,Female,West,Designer,125.95,Yes,Home Decor,Express
6,98,Sienna Riley,26,Female,West,Student,85.3,Yes,Home Decor,Express

In [104]:
for x in df['customer_name']:
    if x[0] == 'S':
        print(x)

Sophia Nguyen
Sofia Phillips
Samuel Morris
Stella Butler
Savannah Sanders
Skylar Ortiz
Sienna Riley

In [118]:
#18. Select the last 8 rows and the first 3 columns.
df.iloc[-8:,0:3]

     id  customer_name  age
92   93  Caleb Gardner   45
93   94    Piper Ellis   25
94   95    Kayden Boyd   37
95   96  Aliyah Holmes   29
96   97  Declan Porter   42
97   98   Sienna Riley   26
98   99  Asher Wallace   34
99  100    Clara Dixon   28

In [126]:
#19. Select 'customer_name' and 'purchase_amount' for customers with purchase_amount between 100 and 200 (inclusive).
df.loc[(df['purchase_amount']>=100) & (df['purchase_amount']<=200), ['customer_name','purchase_amount']]
'''
SEE how in pandas we donot and cannot use 'and' but we have to use '&'
    WHY WE GET THE ERROR: ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
    df['purchase_amount'] >= 100 creates a series which each element True or False, so python tries to get a singlular boolean value for the 
    entire series, which does not make sense.
    & is actually a bit-wise operator, but pandas overwrites the & such that it compares row by row, and not once for the entire seires
    that is why in pandas filtering we use '&' insted of 'and'.
'''

"\nSEE how in pandas we donot and cannot use 'and' but we have to use '&'\n    WHY WE GET THE ERROR: ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().\n    df['purchase_amount'] >= 100 creates a series which each element True or False, so python tries to get a singlular boolean value for the \n    entire series, which does not make sense.\n    & is actually a bit-wise operator, but pandas overwrites the & such that it compares row by row, and not once for the entire seires\n    that is why in pandas filtering we use '&' insted of 'and'.\n"

In [125]:
#20. Select every 4th row from 0 to 60 and columns 3, 6, and 9.

for i in range(3,61,4):
    print(df.iloc[i,[0,3,6,9]])

id                            4
gender                     Male
purchase_amount           175.2
delivery_preference    Standard
Name: 3, dtype: object
id                            8
gender                     Male
purchase_amount           200.6
delivery_preference    Standard
Name: 7, dtype: object
id                           12
gender                     Male
purchase_amount          160.35
delivery_preference    Standard
Name: 11, dtype: object
id                           16
gender                     Male
purchase_amount          280.95
delivery_preference    Standard
Name: 15, dtype: object
id                           20
gender                     Male
purchase_amount          210.25
delivery_preference    Standard
Name: 19, dtype: object
id                           24
gender                     Male
purchase_amount          155.45
delivery_preference    Standard
Name: 23, dtype: object
id                           28
gender                     Male
purchase_amount           195.2
delivery_preference    Standard
Name: 27, dtype: object
id                           32
gender                     Male
purchase_amount          205.65
delivery_preference    Standard
Name: 31, dtype: object
id                           36
gender                     Male
purchase_amount           240.8
delivery_preference    Standard
Name: 35, dtype: object
id                           40
gender                     Male
purchase_amount           275.2
delivery_preference    Standard
Name: 39, dtype: object
id                           44
gender                     Male
purchase_amount           160.3
delivery_preference    Standard
Name: 43, dtype: object
id                           48
gender                     Male
purchase_amount          235.25
delivery_preference    Standard
Name: 47, dtype: object
id                           52
gender                     Male
purchase_amount           280.3
delivery_preference    Standard
Name: 51, dtype: object
id                          56
gender                  Female
purchase_amount          130.8
delivery_preference    Express
Name: 55, dtype: object
id                          60
gender                  Female
purchase_amount         145.15
delivery_preference    Express
Name: 59, dtype: object

In [149]:
#20. Select every 4th row from 0 to 60 and columns 3, 6, and 9.


rf = pd.DataFrame(columns=df.columns)
rf


for i in range(3,61,4):
    rf.loc[len(rf)] =  df.iloc[i]
rf

,id,customer_name,age,gender,region,occupation,purchase_amount,loyalty_program,preferred_category,delivery_preference
0,4,Michael Patel,45,Male,East,Manager,175.2,No,Electronics,Standard
1,8,William Garcia,52,Male,East,Consultant,200.6,No,Electronics,Standard
2,12,Noah Rodriguez,27,Male,East,Engineer,160.35,No,Electronics,Standard
3,16,Alexander Young,49,Male,East,Doctor,280.95,No,Electronics,Standard
4,20,Henry Green,44,Male,East,Consultant,210.25,No,Home Decor,Standard
5,24,Jack Carter,39,Male,East,Teacher,155.45,No,Electronics,Standard
6,28,Mason Turner,35,Male,East,Engineer,195.2,No,Electronics,Standard
7,32,Logan Evans,43,Male,East,Consultant,205.65,No,Electronics,Standard
8,36,Samuel Morris,48,Male,East,Manager,240.8,No,Electronics,Standard
9,40,Joseph Bell,41,Male,East,Doctor,275.2,No,Electronics,Standard
10,44,Owen Rivera,45,Male,East,Teacher,160.3,No,Electronics,Standard
11,48,Isaac Wood,42,Male,East,Manager,235.25,No,Home Decor,Standard
12,52,Julian Hughes,47,Male,East,Doctor,280.3,No,Electronics,Standard
13,56,Aubrey Myers,27,Female,North,Designer,130.8,Yes,Books,Express
14,60,Arianna Price,26,Female,North,Analyst,145.15,Yes,Books,Express

In [151]:
#simplest way
#20. Select every 4th row from 0 to 60 and columns 3, 6, and 9.
df.iloc[3:61:4,[0,3,6,9]]

    id  gender  purchase_amount delivery_preference
3    4    Male           175.20            Standard
7    8    Male           200.60            Standard
11  12    Male           160.35            Standard
15  16    Male           280.95            Standard
19  20    Male           210.25            Standard
23  24    Male           155.45            Standard
27  28    Male           195.20            Standard
31  32    Male           205.65            Standard
35  36    Male           240.80            Standard
39  40    Male           275.20            Standard
43  44    Male           160.30            Standard
47  48    Male           235.25            Standard
51  52    Male           280.30            Standard
55  56  Female           130.80             Express
59  60  Female           145.15             Express

In [168]:
#21. Select 'customer_name', 'occupation', and 'loyalty_program' for customers aged between 20 and 30 (inclusive).

df.loc[(df['age']>=20) & (df['age']<=30),['customer_name', 'occupation', 'loyalty_program','age']]

       customer_name occupation loyalty_program  age
0     Alice Thompson   Engineer             Yes   25
2         Emily Chen   Designer             Yes   28
6       Olivia Brown    Analyst             Yes   29
8       Ava Martinez     Artist             Yes   23
10    Isabella Clark  Marketing             Yes   30
11    Noah Rodriguez   Engineer              No   27
14    Charlotte Hall   Designer             Yes   26
16      Amelia Allen    Student             Yes   21
18      Harper Scott   Engineer             Yes   28
20      Evelyn Adams     Artist             Yes   24
24    Emily Mitchell   Designer             Yes   27
26     Avery Roberts    Student             Yes   22
28    Sofia Phillips    Analyst             Yes   29
30      Grace Parker  Marketing             Yes   26
32   Madison Edwards     Artist             Yes   23
34     Layla Stewart    Teacher             Yes   30
36         Zoey Reed   Designer             Yes   25
38   Penelope Morgan    Analyst             Yes   28
40      Riley Brooks    Student             Yes   24
42       Aria Bailey  Marketing             Yes   27
44        Hannah Cox   Designer             Yes   29
48    Natalie Fisher     Artist             Yes   26
50     Victoria Gray    Student             Yes   24
52        Hazel West  Marketing             Yes   28
54      Lillian Ford    Teacher             Yes   30
55      Aubrey Myers   Designer             Yes   27
57        Ellie Long    Student             Yes   23
59     Arianna Price    Analyst             Yes   26
61  Savannah Sanders  Marketing             Yes   29
63    Aurora Jenkins     Artist             Yes   24
65      Skylar Ortiz   Designer             Yes   27
67       Clara Wells    Analyst             Yes   30
69     Delilah Hayes    Student             Yes   25
71       Maya Hunter  Marketing             Yes   28
73       Nora Hudson   Designer             Yes   26
75        Lydia Cole     Artist             Yes   24
77   Eleanor Russell    Teacher             Yes   29
79     Aria Peterson    Student             Yes   27
81       Lila Murray  Marketing             Yes   25
83   Addison Simmons   Designer             Yes   30
85    Paisley Pierce     Artist             Yes   26
87       Autumn Ford    Teacher             Yes   28
89     Brooklyn Dunn    Student             Yes   24
91        Audrey Fox  Marketing             Yes   27
93       Piper Ellis   Designer             Yes   25
95     Aliyah Holmes    Analyst             Yes   29
97      Sienna Riley    Student             Yes   26
99       Clara Dixon     Artist             Yes   28

In [171]:
#22. Select rows 60 to 70 and the columns corresponding to 'age', 'region', and 'preferred_category'.
df.iloc[60:71,[2,4,-2]]

    age region preferred_category
60   41  South        Electronics
61   29   West         Home Decor
62   36   East           Clothing
63   24  North              Books
64   48  South        Electronics
65   27   West         Home Decor
66   35   East           Clothing
67   30  North              Books
68   42  South        Electronics
69   25   West         Home Decor
70   39   East           Clothing

In [173]:
#23. Select all columns for customers in the East region with purchase_amount less than 150.
df.loc[(df['region'] == 'East'),]23. Select all columns for customers in the East region with purchase_amount less than 150.

,id,customer_name,age,gender,region,occupation,purchase_amount,loyalty_program,preferred_category,delivery_preference
3,4,Michael Patel,45,Male,East,Manager,175.20,No,Electronics,Standard
7,8,William Garcia,52,Male,East,Consultant,200.60,No,Electronics,Standard
11,12,Noah Rodriguez,27,Male,East,Engineer,160.35,No,Electronics,Standard
15,16,Alexander Young,49,Male,East,Doctor,280.95,No,Electronics,Standard
19,20,Henry Green,44,Male,East,Consultant,210.25,No,Home Decor,Standard
23,24,Jack Carter,39,Male,East,Teacher,155.45,No,Electronics,Standard
27,28,Mason Turner,35,Male,East,Engineer,195.20,No,Electronics,Standard
31,32,Logan Evans,43,Male,East,Consultant,205.65,No,Electronics,Standard
35,36,Samuel Morris,48,Male,East,Manager,240.80,No,Electronics,Standard
39,40,Joseph Bell,41,Male,East,Doctor,275.20,No,Electronics,Standard
43,44,Owen Rivera,45,Male,East,Teacher,160.30,No,Electronics,Standard
47,48,Isaac Wood,42,Male,East,Manager,235.25,No,Home Decor,Standard
51,52,Julian Hughes,47,Male,East,Doctor,280.30,No,Electronics,Standard
58,59,Lincoln Foster,39,Male,East,Lawyer,175.60,No,Clothing,Standard
62,63,Joshua Ross,36,Male,East,Engineer,190.25,No,Clothing,Standard
66,67,Jeremiah Gordon,35,Male,East,Teacher,160.50,No,Clothing,Standard
70,71,Eli Henderson,39,Male,East,Lawyer,170.85,No,Clothing,Standard
74,75,Aaron Bryant,37,Male,East,Engineer,195.30,No,Clothing,Standard
78,79,Hudson Duncan,35,Male,East,Analyst,150.80,No,Clothing,Standard
82,83,Ezra Reid,38,Male,East,Lawyer,175.35,No,Clothing,Standard
86,87,Evan Berry,36,Male,East,Engineer,190.65,No,Clothing,Standard
90,91,Adrian Black,39,Male,East,Consultant,210.30,No,Clothing,Standard
94,95,Kayden Boyd,37,Male,East,Lawyer,170.50,No,Clothing,Standard
98,99,Asher Wallace,34,Male,East,Teacher,160.75,No,Clothing,Standard

In [24]:
# 24. Select the first 12 rows and the last 3 columns.
df.iloc[0:12,-3:]

   loyalty_program preferred_category delivery_preference
0              Yes        Electronics             Express
1               No           Clothing            Standard
2              Yes         Home Decor             Express
3               No        Electronics            Standard
4              Yes              Books             Express
5               No           Clothing            Standard
6              Yes         Home Decor             Express
7               No        Electronics            Standard
8              Yes              Books             Express
9               No           Clothing            Standard
10             Yes         Home Decor             Express
11              No        Electronics            Standard

In [26]:
# 25. Select 'customer_name', 'age', and 'delivery_preference' for customers with id in the range 30 to 50.
df.loc[(df['id'] >= 30) & (df['id']<= 50), ['customer_name', 'age', 'delivery_preference'] ]

      customer_name  age delivery_preference
29  Elijah Campbell   40            Standard
30     Grace Parker   26             Express
31      Logan Evans   43            Standard
32  Madison Edwards   23             Express
33    Aiden Collins   37            Standard
34    Layla Stewart   30             Express
35    Samuel Morris   48            Standard
36        Zoey Reed   25             Express
37       David Cook   34            Standard
38  Penelope Morgan   28             Express
39      Joseph Bell   41            Standard
40     Riley Brooks   24             Express
41    Carter Cooper   39            Standard
42      Aria Bailey   27             Express
43      Owen Rivera   45            Standard
44       Hannah Cox   29             Express
45        Luke Ward   36            Standard
46    Stella Butler   31             Express
47       Isaac Wood   42            Standard
48   Natalie Fisher   26             Express
49    Grayson Stone   38            Standard