Pandas : Work with relational and labelled data, manipulation, analysis and cleaning.

In [150]:
'''
To manually store data in a table, create a DataFrame. 
When using a Python dictionary of lists, the dictionary 
keys will be used as column headers and the values in each list as columns 
of the DataFrame.
'''
import pandas as pd
#creating a data frame:
df = pd.DataFrame(
    {
        "Name": ['Harsh', 'Deep', 'Singh'],
        "Age" : [11,23,44],
        "Sex" : ['M', 'F', 'M']
    }
)
df
#each column in a data frame is a series
df["Age"].max()

44

In [151]:
#pandas.DataFrame.Descrive
df.describe()

             Age
count   3.000000
mean   26.000000
std    16.703293
min    11.000000
25%    17.000000
50%    23.000000
75%    33.500000
max    44.000000

Data Structures of Pandas
    1. Frame : 1 Dimensional List (single column table)
    2. DataFrame: 2 Dimensional Table with rows and columns

In [152]:
series = pd.Series([91,22,33,94,5,46,70])
series
#it follows the list slicing and indexing

print(series[3])
series[0:3]

94

0    91
1    22
2    33
dtype: int64

In [153]:
#attribues:
series.index

RangeIndex(start=0, stop=7, step=1)

In [154]:
series.values

array([91, 22, 33, 94,  5, 46, 70])

In [155]:
series.dtype

dtype('int64')

In [156]:
#Methods:
#1. Head
series.head()
print("_______________________________")
series.head(3)

_______________________________

0    91
1    22
2    33
dtype: int64

In [157]:
#2. Tail
series.tail(1)

6    70
dtype: int64

In [158]:
#sorting the values
series.sort_values()

4     5
1    22
2    33
5    46
6    70
0    91
3    94
dtype: int64

In [159]:
series.count()

np.int64(7)

In [160]:
series.isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [161]:
series.notnull()

0    True
1    True
2    True
3    True
4    True
5    True
6    True
dtype: bool

In [162]:
series += 1000
series

0    1091
1    1022
2    1033
3    1094
4    1005
5    1046
6    1070
dtype: int64

In [163]:
test = pd.Series([1,2,None])
test.isnull()
test.notnull()
test = test.fillna(100)
test

0      1.0
1      2.0
2    100.0
dtype: float64

In [164]:
#custom indexing
cin = pd.Series(data = [1,2,3,4,45,4],index = tuple('qwerty'))
cin

q     1
w     2
e     3
r     4
t    45
y     4
dtype: int64

In [165]:
#DATA FRAME (TABLES) IN PANDAS
df = pd.DataFrame( {
        "Name": ['Harsh', 'Deep', 'Singh'],
        "Age" : [11,23,None],
        "Sex" : ['M', 'F', 'M']
    }, index = ['q','w','e'])
s1 = pd.Series([1,2,3,4,45])
s2 = pd.Series([5,3,2,1,2])

mf = pd.DataFrame(
    {
        "top" : s1,
        "Bot" : s2
        
    }
)
df

    Name   Age Sex
q  Harsh  11.0   M
w   Deep  23.0   F
e  Singh   NaN   M

In [166]:
#Attributes

df.shape #gives the shape of the table
series.shape

(7,)

In [167]:
df.columns #returns the name of attribures

Index(['Name', 'Age', 'Sex'], dtype='object')

In [168]:
df.dtypes #returns data type of each columns

Name     object
Age     float64
Sex      object
dtype: object

In [169]:
#Accessing Data via the loc method 
#loc can use lable to get using lables
df.loc[0,'Age'] # 0 row of the 'Age' column
df.loc[2,'Age']

x = df.loc[0:1, 'Age'] # if you don't mention a specific colThe describe() method provides a quick overview of the numerical data in a DataFrame. As the Name and Sex columns are textual data, these are by default not taken into account by the describe() method.umn it will pour out the entire record
#see how range in loc is not end exclusive like it happens in python
#here 0:1 are lables of rows and not the indexes, as they are not traditional indexes that is why it is not range exclusive
df.loc[1,['Name','Sex']] # taking out only specific columns
x

KeyError: 0

In [170]:
#iloc using indexes
df.iloc[0:3, 0:2] # see how iloc works on indexes so it is end exclusive
#we cannot use lables in iloc, only indexes allowed

    Name   Age
q  Harsh  11.0
w   Deep  23.0
e  Singh   NaN

In [171]:
df.head(2)

    Name   Age Sex
q  Harsh  11.0   M
w   Deep  23.0   F

In [172]:
df.tail(1)

    Name  Age Sex
e  Singh  NaN   M

In [173]:
#info() returns the schema of the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, q to e
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     2 non-null      float64
 2   Sex     3 non-null      object
dtypes: float64(1), object(2)
memory usage: 204.0+ bytes

In [174]:
#mathematical kundli of the dataframe
df.describe()

             Age
count   2.000000
mean   17.000000
std     8.485281
min    11.000000
25%    14.000000
50%    17.000000
75%    20.000000
max    23.000000

In [175]:
df.sort_values('Name')

    Name   Age Sex
w   Deep  23.0   F
q  Harsh  11.0   M
e  Singh   NaN   M

In [176]:
#filtering data
df[df['Name'] >'Harsh']

    Name  Age Sex
e  Singh  NaN   M

In [177]:
#Adding, Deleting and Updation
df["class"] = [23,23,23]
df
# del df['Name'] deleting a row
df

    Name   Age Sex  class
q  Harsh  11.0   M     23
w   Deep  23.0   F     23
e  Singh   NaN   M     23

In [178]:
df.loc[df['Age']==11, "Age"] = 90
#in all the records where AGE == 11, set "Name" attribure to "Hello"
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

    Name   Age Sex  class
q  Harsh  90.0   M     23
w   Deep  23.0   F     23
e  Singh   NaN   M     23

In [179]:
df = pd.read_csv("/home/harsh/Documents/jNotebook/Pandas/updated_stu_data.csv")

In [180]:
df

    Unnamed: 0    ID            Name   Age  Grade  Attendance
0            0   1.0      John Smith  16.0   85.0   95.000000
1            1   1.0    Emma Johnson  16.0   90.0   92.000000
2            2   3.0   Michael Brown  17.0   85.0   88.000000
3            3   4.0    James Wilson  15.0   78.0   91.345679
4            4   5.0    James Wilson  16.0   82.0   90.000000
..         ...   ...             ...   ...    ...         ...
95          95  96.0  Ariana Griffin  15.0   78.0   92.000000
96          96  96.0     Connor Ford  16.0   85.0   90.000000
97          97  98.0  Paisley Hansen  16.0   85.0   94.000000
98          98  99.0     Jordan Webb  17.0   87.0   91.345679
99          99  99.0     Jordan Webb  15.0   80.0   91.000000

[100 rows x 6 columns]

In [181]:
df.isnull().sum()

Unnamed: 0    0
ID            0
Name          0
Age           0
Grade         0
Attendance    0
dtype: int64

In [182]:
import numpy as np
x = np.array([[1,2,3],[1,2,3],[1,2,3]])
df = pd.DataFrame(x, columns = ['a','aa','aaa'])
df

   a  aa  aaa
0  1   2    3
1  1   2    3
2  1   2    3

In [183]:
#DATA CLEANING AND PREPROCESSIG
df = pd.read_csv("/home/harsh/Documents/jNotebook/Pandas/updated_stu_data.csv")

In [184]:
df

    Unnamed: 0    ID            Name   Age  Grade  Attendance
0            0   1.0      John Smith  16.0   85.0   95.000000
1            1   1.0    Emma Johnson  16.0   90.0   92.000000
2            2   3.0   Michael Brown  17.0   85.0   88.000000
3            3   4.0    James Wilson  15.0   78.0   91.345679
4            4   5.0    James Wilson  16.0   82.0   90.000000
..         ...   ...             ...   ...    ...         ...
95          95  96.0  Ariana Griffin  15.0   78.0   92.000000
96          96  96.0     Connor Ford  16.0   85.0   90.000000
97          97  98.0  Paisley Hansen  16.0   85.0   94.000000
98          98  99.0     Jordan Webb  17.0   87.0   91.345679
99          99  99.0     Jordan Webb  15.0   80.0   91.000000

[100 rows x 6 columns]

In [185]:
#dropna() drops the entire record if any value is NaN
df.dropna()

    Unnamed: 0    ID            Name   Age  Grade  Attendance
0            0   1.0      John Smith  16.0   85.0   95.000000
1            1   1.0    Emma Johnson  16.0   90.0   92.000000
2            2   3.0   Michael Brown  17.0   85.0   88.000000
3            3   4.0    James Wilson  15.0   78.0   91.345679
4            4   5.0    James Wilson  16.0   82.0   90.000000
..         ...   ...             ...   ...    ...         ...
95          95  96.0  Ariana Griffin  15.0   78.0   92.000000
96          96  96.0     Connor Ford  16.0   85.0   90.000000
97          97  98.0  Paisley Hansen  16.0   85.0   94.000000
98          98  99.0     Jordan Webb  17.0   87.0   91.345679
99          99  99.0     Jordan Webb  15.0   80.0   91.000000

[100 rows x 6 columns]

In [186]:
df

    Unnamed: 0    ID            Name   Age  Grade  Attendance
0            0   1.0      John Smith  16.0   85.0   95.000000
1            1   1.0    Emma Johnson  16.0   90.0   92.000000
2            2   3.0   Michael Brown  17.0   85.0   88.000000
3            3   4.0    James Wilson  15.0   78.0   91.345679
4            4   5.0    James Wilson  16.0   82.0   90.000000
..         ...   ...             ...   ...    ...         ...
95          95  96.0  Ariana Griffin  15.0   78.0   92.000000
96          96  96.0     Connor Ford  16.0   85.0   90.000000
97          97  98.0  Paisley Hansen  16.0   85.0   94.000000
98          98  99.0     Jordan Webb  17.0   87.0   91.345679
99          99  99.0     Jordan Webb  15.0   80.0   91.000000

[100 rows x 6 columns]

In [187]:
df.fillna(100)

    Unnamed: 0    ID            Name   Age  Grade  Attendance
0            0   1.0      John Smith  16.0   85.0   95.000000
1            1   1.0    Emma Johnson  16.0   90.0   92.000000
2            2   3.0   Michael Brown  17.0   85.0   88.000000
3            3   4.0    James Wilson  15.0   78.0   91.345679
4            4   5.0    James Wilson  16.0   82.0   90.000000
..         ...   ...             ...   ...    ...         ...
95          95  96.0  Ariana Griffin  15.0   78.0   92.000000
96          96  96.0     Connor Ford  16.0   85.0   90.000000
97          97  98.0  Paisley Hansen  16.0   85.0   94.000000
98          98  99.0     Jordan Webb  17.0   87.0   91.345679
99          99  99.0     Jordan Webb  15.0   80.0   91.000000

[100 rows x 6 columns]

In [188]:
df

    Unnamed: 0    ID            Name   Age  Grade  Attendance
0            0   1.0      John Smith  16.0   85.0   95.000000
1            1   1.0    Emma Johnson  16.0   90.0   92.000000
2            2   3.0   Michael Brown  17.0   85.0   88.000000
3            3   4.0    James Wilson  15.0   78.0   91.345679
4            4   5.0    James Wilson  16.0   82.0   90.000000
..         ...   ...             ...   ...    ...         ...
95          95  96.0  Ariana Griffin  15.0   78.0   92.000000
96          96  96.0     Connor Ford  16.0   85.0   90.000000
97          97  98.0  Paisley Hansen  16.0   85.0   94.000000
98          98  99.0     Jordan Webb  17.0   87.0   91.345679
99          99  99.0     Jordan Webb  15.0   80.0   91.000000

[100 rows x 6 columns]

In [189]:
#removing duplicated
df = df.drop_duplicates()
df

    Unnamed: 0    ID            Name   Age  Grade  Attendance
0            0   1.0      John Smith  16.0   85.0   95.000000
1            1   1.0    Emma Johnson  16.0   90.0   92.000000
2            2   3.0   Michael Brown  17.0   85.0   88.000000
3            3   4.0    James Wilson  15.0   78.0   91.345679
4            4   5.0    James Wilson  16.0   82.0   90.000000
..         ...   ...             ...   ...    ...         ...
95          95  96.0  Ariana Griffin  15.0   78.0   92.000000
96          96  96.0     Connor Ford  16.0   85.0   90.000000
97          97  98.0  Paisley Hansen  16.0   85.0   94.000000
98          98  99.0     Jordan Webb  17.0   87.0   91.345679
99          99  99.0     Jordan Webb  15.0   80.0   91.000000

[100 rows x 6 columns]

In [137]:
df['Age'].value_counts()

Age
16.0    50
17.0    25
15.0    25
Name: count, dtype: int64

In [190]:
#Type conversion
df['Age'] = df['Age'].astype(int)
df[['Age']]
df['Name'].str.upper()

0         JOHN SMITH
1       EMMA JOHNSON
2      MICHAEL BROWN
3       JAMES WILSON
4       JAMES WILSON
           ...
95    ARIANA GRIFFIN
96       CONNOR FORD
97    PAISLEY HANSEN
98       JORDAN WEBB
99       JORDAN WEBB
Name: Name, Length: 100, dtype: object

In [191]:
df['Name'].str.upper()

0         JOHN SMITH
1       EMMA JOHNSON
2      MICHAEL BROWN
3       JAMES WILSON
4       JAMES WILSON
           ...
95    ARIANA GRIFFIN
96       CONNOR FORD
97    PAISLEY HANSEN
98       JORDAN WEBB
99       JORDAN WEBB
Name: Name, Length: 100, dtype: object

In [192]:
#Data Aggregation and Grouping
df
df['ID'] = df['ID'].astype(int)
df

    Unnamed: 0  ID            Name  Age  Grade  Attendance
0            0   1      John Smith   16   85.0   95.000000
1            1   1    Emma Johnson   16   90.0   92.000000
2            2   3   Michael Brown   17   85.0   88.000000
3            3   4    James Wilson   15   78.0   91.345679
4            4   5    James Wilson   16   82.0   90.000000
..         ...  ..             ...  ...    ...         ...
95          95  96  Ariana Griffin   15   78.0   92.000000
96          96  96     Connor Ford   16   85.0   90.000000
97          97  98  Paisley Hansen   16   85.0   94.000000
98          98  99     Jordan Webb   17   87.0   91.345679
99          99  99     Jordan Webb   15   80.0   91.000000

[100 rows x 6 columns]

In [204]:
group = df.groupby('Name')
group.sum()

                   Unnamed: 0   ID  Age  Grade  Attendance
Name
Aaliyah Wells              83   83   15   85.0   90.000000
Addison Cooper             45   45   16   87.0   89.000000
Aiden Bennett              56   56   16   85.0   90.000000
Alexander King             18   19   17   91.0   91.345679
Allison Hunter            161  163   32  170.0  185.345679
...                       ...  ...  ...    ...         ...
Skylar Myers               69   69   16   87.0   94.000000
Sofia Stewart              37   38   16   84.0   90.000000
Victoria Mitchell          27   28   15   78.0   94.000000
William Anderson            6    6   17   92.0   89.000000
Zoey Cook                  41   42   16   89.0   91.000000

[86 rows x 5 columns]

In [226]:
mf= pd.DataFrame({
    'name' : ['a','b','a','b','c'],
    'lemondae' : (1,2,3,4,5)})
nf= pd.DataFrame({
    'name' : ['a','b','a','b','c'],
    'lemon' : (11,22,33,44,55),
    'lemondae' : (1,2,3,4,5)})


x = pd.concat([mf,nf])
x.loc[0,:]

  name  lemondae  lemon
0    a         1    NaN
0    a         1   11.0

In [221]:
mf.append(nf) #already has been deprecated

AttributeError: 'DataFrame' object has no attribute 'append'

In [234]:

pd.merge(mf,nf, on=['name','lemondae'])

  name  lemondae  lemon
0    a         1     11
1    b         2     22
2    a         3     33
3    b         4     44
4    c         5     55