Pandas Homework

In [78]:
import pandas as pd
df = pd.read_csv("/home/harsh/Documents/jNotebook/Pandas/student_data(3).csv")

In [79]:
df.isnull().sum()

ID            29
Name          14
Age           25
Grade         19
Attendance    19
dtype: int64

In [80]:
df.columns

Index(['ID', 'Name', 'Age', 'Grade', 'Attendance'], dtype='object')

In [81]:
df

      ID            Name   Age  Grade  Attendance
0    1.0      John Smith  16.0   85.0        95.0
1    NaN    Emma Johnson   NaN   90.0        92.0
2    3.0   Michael Brown  17.0    NaN        88.0
3    4.0             NaN  15.0   78.0         NaN
4    5.0    James Wilson  16.0   82.0        90.0
..   ...             ...   ...    ...         ...
95  96.0  Ariana Griffin  15.0   78.0        92.0
96   NaN     Connor Ford  16.0    NaN        90.0
97  98.0  Paisley Hansen   NaN   85.0        94.0
98  99.0     Jordan Webb  17.0   87.0         NaN
99   NaN             NaN  15.0   80.0        91.0

[100 rows x 5 columns]

In [82]:
df['ID'] = df['ID'].fillna(method = 'ffill')
df['Name'] = df['Name'].fillna(method = 'bfill')
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Grade'] = df['Grade'].fillna(df['Grade'].median())
df['Attendance'] = df['Attendance'].fillna(df['Attendance'].mean())
df

/tmp/ipykernel_8509/2300792428.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['ID'] = df['ID'].fillna(method = 'ffill')
/tmp/ipykernel_8509/2300792428.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Name'] = df['Name'].fillna(method = 'bfill')

      ID            Name   Age  Grade  Attendance
0    1.0      John Smith  16.0   85.0   95.000000
1    1.0    Emma Johnson  16.0   90.0   92.000000
2    3.0   Michael Brown  17.0   85.0   88.000000
3    4.0    James Wilson  15.0   78.0   91.345679
4    5.0    James Wilson  16.0   82.0   90.000000
..   ...             ...   ...    ...         ...
95  96.0  Ariana Griffin  15.0   78.0   92.000000
96  96.0     Connor Ford  16.0   85.0   90.000000
97  98.0  Paisley Hansen  16.0   85.0   94.000000
98  99.0     Jordan Webb  17.0   87.0   91.345679
99  99.0             NaN  15.0   80.0   91.000000

[100 rows x 5 columns]

In [83]:
df['Name'] = df['Name'].fillna(method = 'ffill')
df.isnull().sum()

/tmp/ipykernel_8509/2052103210.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Name'] = df['Name'].fillna(method = 'ffill')

ID            0
Name          0
Age           0
Grade         0
Attendance    0
dtype: int64

In [84]:
x = df[['Grade','Attendance']].corr()
x

               Grade  Attendance
Grade       1.000000   -0.266585
Attendance -0.266585    1.000000

In [85]:
df.describe()

               ID         Age       Grade  Attendance
count  100.000000  100.000000  100.000000  100.000000
mean    50.210000   16.000000   84.680000   91.345679
std     28.992265    0.710669    3.416774    1.640156
min      1.000000   15.000000   78.000000   88.000000
25%     25.750000   15.750000   83.000000   90.000000
50%     50.000000   16.000000   85.000000   91.345679
75%     75.250000   16.250000   87.000000   92.000000
max     99.000000   17.000000   92.000000   95.000000

In [88]:
df['Age'] = df['Age'].astype(int)
df[['Age']]

    Age
0    16
1    16
2    17
3    15
4    16
..  ...
95   15
96   16
97   16
98   17
99   15

[100 rows x 1 columns]

In [66]:
#SELECTING WITH CONDITIONS
df[df['Age']>16]

      ID                Name   Age  Grade  Attendance
2    3.0       Michael Brown  17.0   85.0   88.000000
6    6.0    William Anderson  17.0   92.0   89.000000
10  11.0         Liam Garcia  17.0   87.0   90.000000
14  15.0        Jacob Walker  17.0   86.0   91.000000
18  19.0      Alexander King  17.0   91.0   91.345679
22  23.0          Jack Adams  17.0   87.0   91.345679
26  26.0       Samuel Carter  17.0   85.0   88.000000
30  31.0     Benjamin Turner  17.0   90.0   89.000000
34  35.0       Matthew Evans  17.0   88.0   91.345679
38  39.0  Christopher Morris  17.0   86.0   92.000000
42  42.0        Logan Morgan  17.0   91.0   91.345679
46  47.0        Lucas Rivera  17.0   82.0   91.345679
50  51.0          Dylan Ward  17.0   86.0   92.000000
54  55.0     Gabriel Ramirez  17.0   90.0   91.345679
58  59.0       Jackson Perry  17.0   87.0   91.345679
62  62.0    Carter Patterson  17.0   85.0   88.000000
66  67.0        Jayden Hayes  17.0   90.0   89.000000
70  71.0          Isaac Hunt  17.0   82.0   91.345679
74  75.0        Hunter Gomez  17.0   88.0   91.345679
78  78.0        Grayson Ford  17.0   85.0   92.000000
82  83.0         Caleb Dixon  17.0   90.0   91.000000
86  87.0       Nicholas Dean  17.0   82.0   91.345679
90  91.0        Colton Burns  17.0   88.0   92.000000
94  95.0      Ariana Griffin  17.0   90.0   91.345679
98  99.0         Jordan Webb  17.0   87.0   91.345679

In [105]:
#ANOTHER SYNTAX QUERY METHODS
df.query('Age>16')
df.query('Name == "Michael Brown"') # return a DataFrame

     EmployeeID           Name  Age Department        Salary  YearsOfService
2           3.0  Michael Brown   40      Sales  69402.515723             2.0
78         79.0  Michael Brown   38         HR  69402.515723             5.0
163       164.0  Michael Brown   40    Finance  70000.000000             5.0
255       256.0  Michael Brown   40         HR  69402.515723             2.0
347       348.0  Michael Brown   40      Sales  70000.000000             5.0
439       440.0  Michael Brown   40         IT  69402.515723             2.0

In [68]:
#Working with data
df.to_csv('updated_stu_data.csv') #exporting the data
df = pd.read_csv("/home/harsh/Documents/jNotebook/Pandas/updated_stu_data.csv")

In [69]:
df.isnull().sum()

Unnamed: 0    0
ID            0
Name          0
Age           0
Grade         0
Attendance    0
dtype: int64

In [70]:
# import numpy as np
# dic = {
#     'X' : [1,2,3],
#     'Y' : np.array([11,12,122]),
#     'Z' : 100
# }

# df = pd.DataFrame(dic)
# df

In [71]:
df

    Unnamed: 0    ID            Name   Age  Grade  Attendance
0            0   1.0      John Smith  16.0   85.0   95.000000
1            1   1.0    Emma Johnson  16.0   90.0   92.000000
2            2   3.0   Michael Brown  17.0   85.0   88.000000
3            3   4.0    James Wilson  15.0   78.0   91.345679
4            4   5.0    James Wilson  16.0   82.0   90.000000
..         ...   ...             ...   ...    ...         ...
95          95  96.0  Ariana Griffin  15.0   78.0   92.000000
96          96  96.0     Connor Ford  16.0   85.0   90.000000
97          97  98.0  Paisley Hansen  16.0   85.0   94.000000
98          98  99.0     Jordan Webb  17.0   87.0   91.345679
99          99  99.0     Jordan Webb  15.0   80.0   91.000000

[100 rows x 6 columns]

In [76]:
x = np.array([[1,2,3],[1,2,3],[1,2,3]])
df = pd.DataFrame(x, columns = ['a','aa','aaa'])
df

   a  aa  aaa
0  1   2    3
1  1   2    3
2  1   2    3

In [89]:
import pandas as pd
df = pd.read_csv('/home/harsh/Documents/jNotebook/Pandas/employee_data.csv')
df

     EmployeeID              Name   Age Department   Salary  YearsOfService
0           1.0        John Smith  34.0         IT  75000.0             5.0
1           NaN               NaN  28.0         HR  60000.0             3.0
2           3.0     Michael Brown   NaN      Sales      NaN             2.0
3           4.0      Sophia Davis  45.0  Marketing  80000.0             NaN
4           NaN               NaN  36.0        NaN  65000.0             4.0
..          ...               ...   ...        ...      ...             ...
495       496.0    Owen Henderson   NaN         HR      NaN             2.0
496       497.0  Scarlett Coleman  45.0    Finance  68000.0             NaN
497       498.0               NaN  32.0  Marketing      NaN             4.0
498       499.0        Dylan Ward  28.0        NaN  62000.0             3.0
499       500.0      Hazel Brooks   NaN         IT  70000.0             5.0

[500 rows x 6 columns]

In [90]:
df['EmployeeID'] = df['EmployeeID'].fillna(method = 'ffill')
df['Name'] = df['Name'].fillna(df['Name'].mode()[0])
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Department'] = df['Department'].fillna(df['Department'].mode()[0])
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df['YearsOfService'] = df['YearsOfService'].fillna(df['YearsOfService'].mode()[0])


df.isnull().sum()

/tmp/ipykernel_8509/3850682726.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['EmployeeID'] = df['EmployeeID'].fillna(method = 'ffill')

EmployeeID        0
Name              0
Age               0
Department        0
Salary            0
YearsOfService    0
dtype: int64

In [91]:
df

,EmployeeID,Name,Age,Department,Salary,YearsOfService
0,1.0,John Smith,34.0,IT,75000.000000,5.0
1,1.0,Emma Johnson,28.0,HR,60000.000000,3.0
2,3.0,Michael Brown,34.0,Sales,69402.515723,2.0
3,4.0,Sophia Davis,45.0,Marketing,80000.000000,3.0
4,4.0,Emma Johnson,36.0,IT,65000.000000,4.0
...,...,...,...,...,...,...
495,496.0,Owen Henderson,34.0,HR,69402.515723,2.0
496,497.0,Scarlett Coleman,45.0,Finance,68000.000000,3.0
497,498.0,Emma Johnson,32.0,Marketing,69402.515723,4.0
498,499.0,Dylan Ward,28.0,IT,62000.000000,3.0
499,500.0,Hazel Brooks,34.0,IT,70000.000000,5.0

In [94]:
df['Name'] = df['Name'].replace('John Smith','Jhonny')
df

,EmployeeID,Name,Age,Department,Salary,YearsOfService
0,1.0,Jhonny,34.0,IT,75000.000000,5.0
1,1.0,Emma Johnson,28.0,HR,60000.000000,3.0
2,3.0,Michael Brown,34.0,Sales,69402.515723,2.0
3,4.0,Sophia Davis,45.0,Marketing,80000.000000,3.0
4,4.0,Emma Johnson,36.0,IT,65000.000000,4.0
...,...,...,...,...,...,...
495,496.0,Owen Henderson,34.0,HR,69402.515723,2.0
496,497.0,Scarlett Coleman,45.0,Finance,68000.000000,3.0
497,498.0,Emma Johnson,32.0,Marketing,69402.515723,4.0
498,499.0,Dylan Ward,28.0,IT,62000.000000,3.0
499,500.0,Hazel Brooks,34.0,IT,70000.000000,5.0

In [100]:
#replace cell matched iff it belongs to the 'column'
df['Age'] = df['Age'].astype(int)

#replace any matched cell
df = df.replace("Name", "Names")
df = df.replace(34, 40)
df

,EmployeeID,Name,Age,Department,Salary,YearsOfService
0,1.0,Jhonny,40,IT,75000.000000,5.0
1,1.0,Emma Johnson,28,HR,60000.000000,3.0
2,3.0,Michael Brown,40,Sales,69402.515723,2.0
3,4.0,Sophia Davis,45,Marketing,80000.000000,3.0
4,4.0,Emma Johnson,36,IT,65000.000000,4.0
...,...,...,...,...,...,...
495,496.0,Owen Henderson,40,HR,69402.515723,2.0
496,497.0,Scarlett Coleman,45,Finance,68000.000000,3.0
497,498.0,Emma Johnson,32,Marketing,69402.515723,4.0
498,499.0,Dylan Ward,28,IT,62000.000000,3.0
499,500.0,Hazel Brooks,40,IT,70000.000000,5.0

In [103]:
x = df['Age'].mean()

36